# Rubocop style configuration
#
# Following
# https://github.com/SUSE/style-guides/blob/master/Ruby.md

# https://github.com/SUSE/style-guides/blob/master/Ruby.md#strings
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 22

Style/RegexpLiteral:
  MaxSlashes: 0

Style/RescueModifier:
  Enabled: false
