#!/usr/bin/env ruby

# TODO: group similar changes: whitespace

require "English"
require "optparse"

categories = []
options = {
  branch: true,
  once: false
}

op = OptionParser.new do |opts|
  opts.banner = "Usage: rubocopify [options]"
  opts.on("-s", "--style", "Apply Style/* cops (default)") do |_v|
    categories << "Style/.*"
  end
  opts.on("-l", "--lint", "Apply Lint/* cops") do |_v|
    categories << "Lint/.*"
  end
  opts.on("-c", "--cops=REGEXP", "Apply cops matching regexp") do |regexp|
    categories << regexp
  end
  opts.on("-1", "--once", "Only the first cop, don't loop") do |v|
    options[:once] = v
  end
  opts.on("-b", "--no-branch", "Don't create the 'rubocop' branch") do |v|
    options[:branch] = v
  end
end
op.parse!

categories = ["Style/.*"] if categories.empty?
categories = Regexp.new(categories.join("|"))

##################################################################

uncommitted = `git status --porcelain`
unless uncommitted.empty?
  puts uncommitted
  exit 1
end

##################################################################

BRANCH = "rubocop".freeze
def setup_branch
  current_branch = `git describe --all`.chomp
  return if current_branch == "heads/#{BRANCH}"

  system "git checkout #{BRANCH}"
  return if $CHILD_STATUS.success?

  system "git branch #{BRANCH}"
  $CHILD_STATUS.success? || raise
  system "git checkout #{BRANCH}"
  $CHILD_STATUS.success? || raise
end

setup_branch if options[:branch]

##################################################################

YML = ".rubocop.yml".freeze
TODO_YML = ".rubocop_todo.yml".freeze

config_filename = File.exist?(TODO_YML) ? TODO_YML : YML

unless File.exist? YML
  if (File.read "RPMNAME" rescue "").start_with? "yast"
    File.write(YML,
               "# use the shared Yast defaults\n" \
               "inherit_from:\n" \
               "  /usr/share/YaST2/data/devtools/data/rubocop_yast_style.yml\n")
  end

  system "rubocop --auto-gen-config"

  config = (File.read(YML) rescue "") + File.read(TODO_YML)
  File.write(YML, config)
  File.unlink(TODO_YML)

  system "git add #{YML}; git commit --message 'RuboCop: --auto-gen-config'"
end

##################################################################

# @return [String, nil] cop name or nil if there are no more cops to run
def unconfigure_one_cop(categories, config_filename)
  conf = File.read(config_filename)

  cop_config_rx = %r{
    \n
    \n
    \# \s Offense \s count .* \n
    \# \s Cop \s supports \s --auto-correct .* \n
    (?: \# [^\n]* \n )*
    ^ ( #{categories} ) : \n
    (?: . | \n )*?
    \n\n
  }x

  cop_name = nil
  conf.sub!(cop_config_rx) do
    cop_name = Regexp.last_match(1)
    "\n\n"
  end

  if cop_name.nil?
    puts "No more autocorrectable cops of category #{categories}."
    return nil
  end

  File.write(config_filename, conf)
  cop_name
end

# @return [Boolean] false if there are no more cops to run
def apply_one_cop(categories, config_filename)
  cop_name = unconfigure_one_cop(categories, config_filename)
  return false if cop_name.nil?

  puts cop_name
  system "rubocop --auto-correct"
  system "git commit --all --message 'RuboCop autocorrected: #{cop_name}'"
  system "git show | cat"

  true
end

loop do
  apply_one_cop(categories, config_filename) || break
  break if options[:once]
end
